# Modify name if deploying multiple instances
name = "sub-box"

main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# [placement]
# mode = "smart"

# Environment variables
# Modify these to use the correct environment variables
[vars]
ADMIN_USERNAME = "alone"
ADMIN_PASSWORD = "aloneicymoon" # Change this to a secure password
JWT_SECRET = "c9346ffb3fe84aceb47cbb00fa67743b" # Change this to a secure secret key
SESSION_TAG = "0"
SESSION_DURATION = "604800"
DEPLOY_TARGET = "cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "prod-sub-box-db" # Change this to the name of your D1 database
database_id = "e9c64f2c-f8f3-4395-9ae0-bb878601330f" # wrangler d1 info <YOUR_DATABASE_NAME>

[observability.logs]
enabled = true

# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "prod-sub-box-next-inc-cache"
